use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'testFramework_Example' do
  pod 'testFramework', :path => '../'
  #远程源码依赖
#  pod 'testFramework', :git => 'https://github.com/waitWindComing/testFramework.git'

  target 'testFramework_Tests' do
    inherit! :search_paths

    pod 'HandyJSON'
  end
  
  # Swift 版本声明
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['HandyJSON'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '5.0'
                  config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              end
              else
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '4.0'
                  config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              end
          end
      end
  end

end
